apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: myapp
  name: myapp
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      run: myapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: myapp
    spec:
      containers:
      - env:
        image: yarashehab/angularapp:v1.0
        imagePullPolicy: Always
        name: myapp
      imagePullSecrets:
        - name: dockerhubreg
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
